# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Deploy with Maven

on:
  push:
    branches: [ "releases" ]
  pull_request:
    branches: ["releases"]
  workflow_dispatch:

jobs:
  build:

    name: Deploy Netron
    runs-on: macos-latest
    
    steps:
    # - uses: actions/checkout@v4
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: maven
    
    - name: Maven Central Release Action
  # You may pin to the exact commit or the version.
  # uses: QubitPi/maven-central-release-action@9cba3841e37f61869adb49fa2187f0f65d96a6cc
      uses: QubitPi/maven-central-release-action@0.0.8
      with:
    # JDK version. Default to 17
        # java-version: # optional, default is 17
    # Java distribution. Default to adopt
        # distribution: # optional, default is adopt
    # The username of the GitHub user who has write access to push tags
        user: chonmb
    # The emails linked to the user on GitHub
        email: weichonmb@foxmail.com
    # The name of the GPG key to sign the released artifact
        gpg-keyname: chonmb
    # GPG private key to import
        gpg-private-key: ${{ secrets.MAVEN_DEPLOY }}
    # Environment variable name for the GPG private key passphrase
        gpg-passphrase: ${{ secrets.PWD }}
    # Maven Central token username
        server-username: ${{ secrets.MAVEN_CENTRAL_NAME }}
    # Maven Central token password
        server-password: ${{ secrets.MAVEN_CENTRAL_PWD }}
          
    # - name: Import GPG key
    #   uses: crazy-max/ghaction-import-gpg@v6.1.0
    #   with:
    #     gpg_private_key: ${{ secrets.MAVEN_DEPLOY }}
    #     passphrase: ${{ secrets.PWD }}
    #     trust_level: 5
    #     git_config_global: true
      
    # - name: show gpg
    #   run: gpg --list-keys
      
    # - name: Build with Maven
    #   run: mvn deploy

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
     # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
